Add author class unit test
henokkhm/microverse-module-4-ruby-group-capstone pull request #49
Opened 2023-10-04 21:51 UTC by Eccb7

In this pull request, I have added the tests on the author class which is passing.

2023-10-04 22:14 UTC, henokkhm requested changes
Hi @Eccb7  Good job thus far. Please address the issues below and we can move on with implementing the remaining features.  Currently, one cannot create a Game object because an error is thrown. Thanks!

2023-10-04 22:14 UTC, henokkhm commented on classes/author.rb
> +  end
Please pull the changes from the other branch. I have already done a code review on this.

2023-10-04 22:14 UTC, henokkhm commented on classes/game.rb
> +    super()
The constructor of the Item class expects two arguments.
Currently, trying to create a Game object throws the following error.

![image](https://github.com/henokkhm/microverse-module-4-ruby-group-capstone/assets/110997325/27ad5a3e-db4c-47f2-b780-99024ffae96a)

2023-10-04 22:14 UTC, henokkhm commented on spec/author_spec.rb
> +
I think you can add a test that checks that the **item** is added to the **items** array when the add_item method is called.

2023-10-05 11:42 UTC, Eccb7 commented
Hi @henokkhm 
You can check this branch and re-review it please

2023-10-05 14:26 UTC, henokkhm approved these changes
Hi @Eccb7 

## Status: Approved

Thanks for making the changes! You can now merge your code.

2023-10-05 14:27 UTC, merged